spring:
  application:
    name: bill-assistant

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false

  sql:
    init:
      mode: NEVER

  jackson:
    mapper:
      accept-case-insensitive-enums: true

  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: NEVER

    vertex:
      ai:
        embedding:
          project-id: ${VERTEX_PROJECT_ID:gc-vertex-spring-ai-project}
          location: ${VERTEX_LOCATION:us-central1}
          text:
            options:
              model: ${VERTEX_EMBEDDING_MODEL:text-embedding-004}

        gemini:
          project-id: ${VERTEX_PROJECT_ID:gc-vertex-spring-ai-project}
          location: ${VERTEX_LOCATION:us-central1}
          chat:
            options:
              model: ${VERTEX_GEMINI_MODEL:gemini-2.0-flash}
              temperature: 0.5

    vectorstore:
      pgvector:
        initialize-schema: false
        remove-existing-vector-store-table: false   # ðŸ”’ CRITICAL
        index-type: HNSW
        dimensions: 768
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000

server:
  port: 8080
  shutdown: GRACEFUL
  servlet:
    context-path: /assistant

logging:
  level:
    org.springframework.web: INFO
    org.springframework.ai: INFO
    org.springframework.boot.context.config: INFO